(add-hook 'hs-mode-hook
          (lambda ()
            (interactive)
            (define-key hs-mode-map (kbd "C-c C-c") 'hs-cabal-build-interactive)
            (define-key hs-mode-map (kbd "C-c c") 'hs-cabal-ido-interactive)
            (define-key hs-mode-map (kbd "C-c t") 'hs-cabal-script-interactive)
            (define-key hs-mode-map (kbd "C-c C-t") 'hs-process-type-of-interactive)
            (define-key hs-mode-map (kbd "C-c C-i") 'hs-process-info-of-interactive)
            (define-key hs-mode-map (kbd "<f5>")
              (lambda ()
                (interactive)
                (when (buffer-modified-p)
                  (save-buffer))
                (hs-process-load-interactive)))
            (define-key hs-mode-map (kbd "\C-x\C-s")
              (lambda ()
                (interactive)
                (when (buffer-modified-p)
                  (save-buffer)
                  (hs-tags-generate-interactive))))
            (define-key hs-mode-map (kbd "<return>") 'hs-mode-newline-same-col)
            (define-key hs-mode-map (kbd "C-<return>") 'hs-mode-newline-indent)
            (define-key hs-mode-map (kbd "C-<left>")
              (lambda ()
                (interactive)
                (hs-move-nested -1)))
            (define-key hs-mode-map (kbd "C-<right>")
              (lambda ()
                (interactive)
                (hs-move-nested 1)))
            (define-key hs-mode-map (kbd "\"") 'paredit-doublequote)
            (define-key hs-mode-map (kbd "[") 'paredit-open-square)
            (define-key hs-mode-map (kbd "(") 'paredit-open-round)
            (define-key hs-mode-map (kbd "]") 'paredit-close-square)
            (define-key hs-mode-map (kbd ")") 'paredit-close-round)
            (define-key hs-mode-map (kbd "{") 'paredit-open-curly)
            (define-key hs-mode-map (kbd "}") 'paredit-close-curly)
            (define-key hs-mode-map (kbd "M-(") 'paredit-wrap-round)
            (define-key hs-mode-map (kbd "DEL") 'paredit-backward-delete)
            (define-key hs-mode-map (kbd "C-k") 'paredit-kill)
            (define-key hs-mode-map (kbd "M-[") 'paredit-wrap-square)
            (define-key hs-mode-map (kbd "C-j") 'paredit-newline)
            (define-key hs-mode-map [f8] 'hs-navigate-imports)))
